const fs = require('fs');
const path = require('path');

const projectRoot = path.resolve(__dirname, '..');

const searchExts = ['.ts', '.tsx', '.js', '.jsx', '.cjs', '.mjs'];
const searchPaths = [
  path.join(projectRoot, 'apps', 'web', 'src'),
  path.join(projectRoot, 'packages')
];

let totalNoUnusedVars = 0;
let generatedNoUnusedVars = 0;

function scanDir(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name !== 'node_modules' && entry.name !== '.next') {
        scanDir(fullPath);
      }
    } else if (searchExts.some(ext => entry.name.endsWith(ext))) {
      const content = fs.readFileSync(fullPath, 'utf8');
      const lines = content.split('\n');
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (line.includes('eslint-disable-next-line @typescript-eslint/no-unused-vars')) {
          totalNoUnusedVars++;
          if (line.trim() === '// eslint-disable-next-line @typescript-eslint/no-unused-vars') {
            generatedNoUnusedVars++;
          }
        }
      }
    }
  }
}

for (const p of searchPaths) {
  if (fs.existsSync(p)) scanDir(p);
}

console.log(`Total @typescript-eslint/no-unused-vars suppressions: ${totalNoUnusedVars}`);
console.log(`Generated by fix_unused_exact.js (exact match): ${generatedNoUnusedVars}`);
