import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'

/**
 * apps/web ESLint configuration — Next.js 16.2.9 native flat config.
 *
 * NO broad rule suppressions.
 * Rule severities are determined by the eslint-config-next presets.
 * Narrow overrides are provided only for rules where the preset's
 * default does not match the project's documented policy decision.
 *
 * Documented policy decisions:
 * - react-hooks/rules-of-hooks: KEPT at preset default (error)
 * - react-hooks/exhaustive-deps: KEPT at preset default (error)
 * - All other rules: preset defaults apply
 *
 * Files genuinely out of scope for linting (generated output or
 * environment declarations):
 * - .next/**            Next.js build output (generated)
 * - next-env.d.ts       Generated by Next.js CLI (generated)
 * - node_modules/**     Third-party vendor code
 * - .turbo/**           Turborepo cache
 * - coverage/**         Test coverage output
 * - out/**              Static export output (generated)
 * - dist/**             Package distribution output (generated)
 */
const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    '.next/**',
    'next-env.d.ts',
    'node_modules/**',
    '.turbo/**',
    'coverage/**',
    'out/**',
    'dist/**',
    '*.mjs',
    '*.js',
    'verify-blob.mjs',
  ]),
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_'
        }
      ],
      '@typescript-eslint/no-explicit-any': 'off',
      '@next/next/no-img-element': 'off'
    }
  }
])

export default eslintConfig
