import { SpatialSection, SpatialOctagonConfig } from './spatial-experience.types';

export const SPATIAL_OCTAGON_CONFIG: SpatialOctagonConfig = {
  faceCount: 8,
  angleStep: (2 * Math.PI) / 8, // 45 degrees (PI / 4)
  radius: 5.2,
  faceWidth: 12.0,
  faceHeight: 4.308, // 2 * 5.2 * Math.tan(Math.PI / 8)
  hubCounterRotationRatio: -0.30, // 30% counter-rotation for mechanical parallax
  cameraZ: 7.8,
  cameraFov: 48,
  pinHeightVh: 700, // 7 steps of 100vh
};

export const DEFAULT_SPATIAL_SECTIONS: SpatialSection[] = [
  {
    id: 'face-discover',
    slug: 'discover',
    sectionNumber: '01',
    eyebrowEn: 'The Experience Engine',
    eyebrowAr: 'محرك التجارب والترفيه',
    headingEn: 'Where Imagination Takes Physical Form',
    headingAr: 'حيث يتجسد الخيال في واقع استثنائي',
    descriptionEn: 'E3 is Qatar’s pioneering creator of large-scale entertainment landmarks, kinetic event engineering, and world-record family attractions.',
    descriptionAr: 'إي ثري هي الوجهة الرائدة في قطر لابتكار وتطوير المعالم الترفيهية الكبرى، وهندسة الفعاليات الاستثنائية، والأرقام القياسية العالمية.',
    primaryCtaLabelEn: 'Explore Attractions',
    primaryCtaLabelAr: 'استكشف الوجهات',
    primaryCtaUrl: '/b2c/attractions',
    secondaryCtaLabelEn: 'Our Story',
    secondaryCtaLabelAr: 'قصتنا ورؤيتنا',
    secondaryCtaUrl: '/b2c/discover',
    media: {
      type: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=1200&auto=format&fit=crop',
      posterUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=1200&auto=format&fit=crop',
      altEn: 'E3 Qatar Event Engineering Landmark',
      altAr: 'معلم ترفيهي من هندسة إي ثري قطر',
    },
    backgroundColor: '#0a0d14',
    accentColor: '#38bdf8', // Cyan / Sky blue
    haloColor: '#0284c7',
    textAlignment: 'LEFT',
    themeMode: 'DARK',
    visibility: true,
    sortOrder: 0,
    stats: [
      { valueEn: '34+', valueAr: '+٣٤', labelEn: 'Flagship Attractions', labelAr: 'وجهة ترفيهية رائدة' },
      { valueEn: '2M+', valueAr: '+٢ مليون', labelEn: 'Joyful Visitors', labelAr: 'زائر سعيد سنوياً' },
    ],
    tags: [
      { labelEn: 'World Record Holders', labelAr: 'حاملو أرقام غينيس' },
      { labelEn: 'Qatar National Vision', labelAr: 'رؤية قطر الوطنية' },
    ],
  },
  {
    id: 'face-attractions',
    slug: 'attractions',
    sectionNumber: '02',
    eyebrowEn: 'Flagship Entertainment',
    eyebrowAr: 'وجهات ترفيهية متكاملة',
    headingEn: 'Next-Gen Amusement, Mega Inflatables & Kinetic Worlds',
    headingAr: 'مغامرات الجيل القادم، عوالم هوائية ومناطق حركية',
    descriptionEn: 'From the Guinness World Record InflataRUN to the adrenaline-pumping Urban Arena at Doha Mall, discover 34 immersive entertainment universes across Qatar.',
    descriptionAr: 'من مضمار إنفلاتارن صاحب الرقم القياسي العالمي إلى أوربان أرينا في دوحة مول، استكشف ٣٤ عالماً ترفيهياً غامراً في جميع أنحاء قطر.',
    primaryCtaLabelEn: 'View 34 Attractions',
    primaryCtaLabelAr: 'تصفح ٣٤ وجهة ترفيهية',
    primaryCtaUrl: '/b2c/attractions',
    secondaryCtaLabelEn: 'Plan Your Visit',
    secondaryCtaLabelAr: 'خطط لزيارتك',
    secondaryCtaUrl: '/b2c/calendar',
    media: {
      type: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=1200&auto=format&fit=crop',
      posterUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=1200&auto=format&fit=crop',
      altEn: 'Urban Arena at Doha Mall',
      altAr: 'أوربان أرينا في دوحة مول',
    },
    backgroundColor: '#0c0f1d',
    accentColor: '#10b981', // Emerald green
    haloColor: '#059669',
    textAlignment: 'LEFT',
    themeMode: 'DARK',
    visibility: true,
    sortOrder: 1,
    stats: [
      { valueEn: '100%', valueAr: '١٠٠٪', labelEn: 'Certified Safety', labelAr: 'معايير أمان معتمدة' },
      { valueEn: '10+', valueAr: '+١٠', labelEn: 'Story Tracks', labelAr: 'مسارات تجارب' },
    ],
    tags: [
      { labelEn: 'InflataRUN', labelAr: 'إنفلاتارن' },
      { labelEn: 'Urban Arena', labelAr: 'أوربان أرينا' },
      { labelEn: 'Doha Mall Anchor', labelAr: 'دوحة مول' },
    ],
  },
  {
    id: 'face-events',
    slug: 'events',
    sectionNumber: '03',
    eyebrowEn: 'Live Calendar & Ticketing',
    eyebrowAr: 'جدول الفعاليات والتذاكر',
    headingEn: 'Festivals, Touring Pop-Ups & Record-Breaking Runs',
    headingAr: 'مهرجانات كبرى، جولات تفاعلية ومسابقات عالمية',
    descriptionEn: 'Instant access to live dates, session bookings, seasonal celebrations, and exclusive ticketing passes for Qatar’s most anticipated gatherings.',
    descriptionAr: 'حجز فوري للفعاليات المباشرة، الجلسات العائلية، الاحتفالات الموسمية، وبطاقات الدخول الحصرية لأبرز فعاليات قطر.',
    primaryCtaLabelEn: 'Browse Events & Tickets',
    primaryCtaLabelAr: 'استعرض الفعاليات والتذاكر',
    primaryCtaUrl: '/b2c/calendar',
    secondaryCtaLabelEn: 'Seasonal Passes',
    secondaryCtaLabelAr: 'الباقات الموسمية',
    secondaryCtaUrl: '/b2c/packages',
    media: {
      type: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1200&auto=format&fit=crop',
      posterUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1200&auto=format&fit=crop',
      altEn: 'InflataRUN Qatar Festival',
      altAr: 'مهرجان إنفلاتارن قطر',
    },
    backgroundColor: '#170c24',
    accentColor: '#ec4899', // Hot pink / Magenta
    haloColor: '#db2777',
    textAlignment: 'LEFT',
    themeMode: 'DARK',
    visibility: true,
    sortOrder: 2,
    stats: [
      { valueEn: '24/7', valueAr: '٢٤/٧', labelEn: 'Instant Digital Tickets', labelAr: 'تذاكر رقمية فورية' },
      { valueEn: '12+', valueAr: '+١٢', labelEn: 'Annual Festivals', labelAr: 'مهرجانات سنوية' },
    ],
    tags: [
      { labelEn: 'Instant Pass', labelAr: 'دخول فوري' },
      { labelEn: 'Apple Wallet Ready', labelAr: 'متوافق مع المحفظة' },
    ],
  },
  {
    id: 'face-packages',
    slug: 'packages',
    sectionNumber: '04',
    eyebrowEn: 'VIP & Group Experiences',
    eyebrowAr: 'باقات كبار الشخصيات والمجموعات',
    headingEn: 'Curated Passes, Private Celebrations & School Tours',
    headingAr: 'باقات مخصصة، احتفالات خاصة ورحلات مدرسية',
    descriptionEn: 'All-inclusive multi-attraction access, customized birthday packages with dedicated party hosts, and VIP hospitality passes with tiered group discounts.',
    descriptionAr: 'دخول شامل لوجهات متعددة، باقات أعياد ميلاد مخصصة مع منسقين محترفين، وتجارب ضيافة VIP مع خصومات مجزية للمجموعات.',
    primaryCtaLabelEn: 'Explore Packages',
    primaryCtaLabelAr: 'استكشف الباقات المتاحة',
    primaryCtaUrl: '/b2c/packages',
    secondaryCtaLabelEn: 'Custom Group Quote',
    secondaryCtaLabelAr: 'طلب عرض سعر خاص',
    secondaryCtaUrl: '/b2c/packages#custom-quote',
    media: {
      type: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=1200&auto=format&fit=crop',
      posterUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=1200&auto=format&fit=crop',
      altEn: 'E3 Birthday & VIP Celebrations',
      altAr: 'احتفالات أعياد الميلاد وباقات VIP',
    },
    backgroundColor: '#181206',
    accentColor: '#f59e0b', // Amber / Gold
    haloColor: '#d97706',
    textAlignment: 'LEFT',
    themeMode: 'DARK',
    visibility: true,
    sortOrder: 3,
    stats: [
      { valueEn: '5-Tier', valueAr: '٥ مستويات', labelEn: 'Curated Categories', labelAr: 'فئات وباقات متنوعة' },
      { valueEn: 'Up to 30%', valueAr: 'حتى ٣٠٪', labelEn: 'Group Savings', labelAr: 'توفير للمجموعات' },
    ],
    tags: [
      { labelEn: 'Birthday Blast', labelAr: 'أعياد الميلاد' },
      { labelEn: 'School Trips', labelAr: 'الرحلات المدرسية' },
      { labelEn: 'VIP Multi-Pass', labelAr: 'الباقة الشاملة VIP' },
    ],
  },
  {
    id: 'face-brands',
    slug: 'brands',
    sectionNumber: '05',
    eyebrowEn: 'Signature Brands & Locations',
    eyebrowAr: 'علاماتنا الحصرية ومواقعنا في قطر',
    headingEn: 'InflataRUN, Urban Arena, Crayons & Bricks & Premier Doha Malls',
    headingAr: 'إنفلاتارن، أوربان أرينا، كرايونز آند بريكس وأرقى مولات الدوحة',
    descriptionEn: 'Explore the proprietary entertainment brands created by E3, located across Doha Mall, Place Vendôme, Katara, and Qatar’s prime destinations.',
    descriptionAr: 'اكتشف العلامات الترفيهية المطورة ذاتياً بواسطة إي ثري، الموزعة في دوحة مول، بلاس فاندوم، كتارا، وأرقى معالم قطر.',
    primaryCtaLabelEn: 'Explore Brands & Malls',
    primaryCtaLabelAr: 'استكشف العلامات والمواقع',
    primaryCtaUrl: '/b2c#ourBrands',
    secondaryCtaLabelEn: 'Interactive Qatar Map',
    secondaryCtaLabelAr: 'خريطة قطر التفاعلية',
    secondaryCtaUrl: '/b2c#qatar-map',
    media: {
      type: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop',
      posterUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop',
      altEn: 'E3 Brands and Qatar GIS Map',
      altAr: 'علامات إي ثري وخارطة قطر التفاعلية',
    },
    backgroundColor: '#07161b',
    accentColor: '#06b6d4', // Cyan
    haloColor: '#0891b2',
    textAlignment: 'LEFT',
    themeMode: 'DARK',
    visibility: true,
    sortOrder: 4,
    stats: [
      { valueEn: '8+', valueAr: '+٨', labelEn: 'Original Brands', labelAr: 'علامات تجارية مبتكرة' },
      { valueEn: 'GIS Live', valueAr: 'تحديد دقيق', labelEn: 'Mall Floor Nav', labelAr: 'ملاحة داخل المولات' },
    ],
    tags: [
      { labelEn: 'Doha Mall Anchor', labelAr: 'دوحة مول' },
      { labelEn: 'Place Vendôme', labelAr: 'بلاس فاندوم' },
    ],
  },
  {
    id: 'face-vault',
    slug: 'vault',
    sectionNumber: '06',
    eyebrowEn: 'Memory Archive & Stories',
    eyebrowAr: 'أرشيف الذكريات والتجارب',
    headingEn: 'Interactive Story Tracks, Digital Badges & Media Vault',
    headingAr: 'مسارات سرد تفاعلية، أوسمة رقمية وخزانة وسائط غامرة',
    descriptionEn: 'Immerse yourself in high-definition memory reels, visitor leaderboards, exclusive achievement badges, and behind-the-scenes engineering retrospectives.',
    descriptionAr: 'استمتع بأشرطة الذكريات عالية الدقة، قوائم المتصدرين، أوسمة الإنجاز الرقمية، وتفاصيل الكواليس الهندسية لصناعة الفعاليات.',
    primaryCtaLabelEn: 'Open Memory Vault',
    primaryCtaLabelAr: 'افتح أرشيف الذكريات',
    primaryCtaUrl: '/b2c#memories',
    secondaryCtaLabelEn: 'Story Tracks',
    secondaryCtaLabelAr: 'مسارات التجارب',
    secondaryCtaUrl: '/b2c#storyTracks',
    media: {
      type: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?q=80&w=1200&auto=format&fit=crop',
      posterUrl: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?q=80&w=1200&auto=format&fit=crop',
      altEn: 'E3 Guest Memories and Media Vault',
      altAr: 'أرشيف ذكريات الزوار وخزانة الوسائط',
    },
    backgroundColor: '#190a1f',
    accentColor: '#a855f7', // Purple / Violet
    haloColor: '#9333ea',
    textAlignment: 'LEFT',
    themeMode: 'DARK',
    visibility: true,
    sortOrder: 5,
    stats: [
      { valueEn: '50K+', valueAr: '+٥٠ ألف', labelEn: 'Guest Photos & Reels', labelAr: 'صورة ومقطع فيديو للزوار' },
      { valueEn: '4K', valueAr: '4K', labelEn: 'Cinematic Visuals', labelAr: 'محتوى سينمائي فائق الدقة' },
    ],
    tags: [
      { labelEn: 'Guest Spotlight', labelAr: 'قصص الزوار' },
      { labelEn: 'Digital Badges', labelAr: 'أوسمة الإنجاز' },
    ],
  },
  {
    id: 'face-careers',
    slug: 'careers',
    sectionNumber: '07',
    eyebrowEn: 'Join The Builders',
    eyebrowAr: 'انضم إلى نخبة الصناع',
    headingEn: 'Shape the Future of Qatar’s Entertainment Industry',
    headingAr: 'اصنع مستقبل صناعة الترفيه والفعاليات في قطر',
    descriptionEn: 'We are seeking world-class event producers, safety engineers, creative technologists, and guest experience masters to build international-grade landmarks.',
    descriptionAr: 'نبحث عن نخبة من مديري الفعاليات، مهندسي السلامة، المبتكرين التقنيين، وخبراء تجربة الزوار لبناء معالم ترفيهية بمواصفات عالمية.',
    primaryCtaLabelEn: 'View Open Roles',
    primaryCtaLabelAr: 'استكشف الوظائف الشاغرة',
    primaryCtaUrl: '/careers',
    secondaryCtaLabelEn: 'Talent Network',
    secondaryCtaLabelAr: 'شبكة الكفاءات',
    secondaryCtaUrl: '/careers#talent-pool',
    media: {
      type: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1200&auto=format&fit=crop',
      posterUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1200&auto=format&fit=crop',
      altEn: 'E3 Engineering and Production Team',
      altAr: 'فريق الهندسة والإنتاج في إي ثري',
    },
    backgroundColor: '#0a1715',
    accentColor: '#14b8a6', // Teal
    haloColor: '#0d9488',
    textAlignment: 'LEFT',
    themeMode: 'DARK',
    visibility: true,
    sortOrder: 6,
    stats: [
      { valueEn: '15+', valueAr: '+١٥', labelEn: 'Nationalities', labelAr: 'جنسية ضمن فريقنا' },
      { valueEn: 'Top 1%', valueAr: 'أفضل ١٪', labelEn: 'Engineering Standards', labelAr: 'معايير هندسية رائدة' },
    ],
    tags: [
      { labelEn: 'Event Producers', labelAr: 'منتجو فعاليات' },
      { labelEn: 'Safety Engineers', labelAr: 'مهندسو سلامة' },
      { labelEn: 'Creative Technologists', labelAr: 'تقنيون مبدعون' },
    ],
  },
  {
    id: 'face-b2b',
    slug: 'b2b',
    sectionNumber: '08',
    eyebrowEn: 'Enterprise & Government Solutions',
    eyebrowAr: 'حلول الشركات والمؤسسات الحكومية',
    headingEn: 'Let’s Build Something Extraordinary Together',
    headingAr: 'لنصنع معاً تجارب استثنائية تفوق التوقعات',
    descriptionEn: 'From turnkey national day celebrations and mega inflatable arenas to bespoke corporate fan zones, partner with Qatar’s proven experiential architects.',
    descriptionAr: 'من احتفالات اليوم الوطني المتكاملة والملاعب الهوائية العملاقة إلى مناطق المشجعين الفاخرة، شارك رواد الهندسة التجريبية في قطر.',
    primaryCtaLabelEn: 'B2B Case Studies',
    primaryCtaLabelAr: 'دراسات الحالة ومشاريع B2B',
    primaryCtaUrl: '/b2b',
    secondaryCtaLabelEn: 'Partner With Us',
    secondaryCtaLabelAr: 'تواصل مع فريق الأعمال',
    secondaryCtaUrl: '/b2b/contact',
    media: {
      type: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=1200&auto=format&fit=crop',
      posterUrl: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=1200&auto=format&fit=crop',
      altEn: 'E3 Enterprise Event Production',
      altAr: 'إنتاج فعاليات الشركات من إي ثري',
    },
    backgroundColor: '#13111c',
    accentColor: '#818cf8', // Indigo
    haloColor: '#6366f1',
    textAlignment: 'LEFT',
    themeMode: 'DARK',
    visibility: true,
    sortOrder: 7,
    stats: [
      { valueEn: '100% Turnkey', valueAr: '١٠٠٪ متكامل', labelEn: 'Design to Execution', labelAr: 'من التصميم إلى التنفيذ' },
      { valueEn: 'Gov & VIP', valueAr: 'جهات حكومية وVIP', labelEn: 'Trusted Partner', labelAr: 'شريك موثوق' },
    ],
    tags: [
      { labelEn: 'Government Activations', labelAr: 'مشاريع حكومية' },
      { labelEn: 'Mega Arenas', labelAr: 'ملاعب عملاقة' },
      { labelEn: 'Turnkey Production', labelAr: 'إنتاج متكامل' },
    ],
  },
];
